### ISSUE TITLE
Issue usin OPENNI on ubuntu 18.04.6

### ISSUE THREAD

**Issue by Okilele56** [Terabee/python_openni2_samples#4]
Hello 
I am trying to use your 3Dcam following this documentation : https://github.com/Terabee/python_openni2_samples

I am using ubuntu 18 and python3. But unfortunatly I have an issue wtith the line openni2.Device.open_any(), the python script do not detect any sensor. 
I have this error message : 
Traceback (most recent call last):
  File "test_openni.py", line 11, in <module>
    dev = openni2.Device.open_any()
  File "/home/banc-terabee/.local/lib/python3.6/site-packages/openni/openni2.py", line 258, in open_any
    return cls(None)
  File "/home/banc-terabee/.local/lib/python3.6/site-packages/openni/openni2.py", line 223, in __init__
    self._reopen()
  File "/home/banc-terabee/.local/lib/python3.6/site-packages/openni/openni2.py", line 233, in _reopen
    c_api.oniDeviceOpen(self._orig_uri, ctypes.byref(self._handle))
  File "/home/banc-terabee/.local/lib/python3.6/site-packages/openni/_openni2.py", line 2837, in wrapper
    raise OpenNIError(res, msg.strip(), logfile)
openni.utils.OpenNIError: (OniStatus.ONI_STATUS_ERROR, b'DeviceOpen using default: no devices found', None)

**Comment by pl-kabaradjian** [comment]
Hello @Okilele56 ,

I invite you to contact our support [here](https://www.terabee.com/contact/) with details about your sensor/setup.
